### PR TITLE
feat: add option to set cookies before visiting loginUrl

### PR DESCRIPTION
**Pull request by Pascalmh**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

We needed to set a cookie so our feature(toggle) was enabled and the social login could be done as expected

## How Has This Been Tested?

I tested it locally with my actual cypress project

## Checklist:

- [x] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I added a picture of a cute animal cause it's fun

image

### CODE REVIEW

**Review by lirantal — APPROVED** [review]
Looks great!

**Comment by lirantal** [comment]
This is awesome. Thank you Pascal 🙌

**Comment by Pascalmh** [comment]
@lirantal that was fast! Thank you - I just upgraded to v1.14.0 in our cypress project, added the `preVisitLoginUrlSetCookies`-option and our test works 🟢 

Thanks for this Plugin, helps us ship our work with confidence!

**Comment by lirantal** [comment]
That's awesome @Pascalmh, thanks for sharing, and I'm happy here to help support it :)

Curious - are you actually running it on CI or just on local dev machines? there has been some issues with social connecting providers due to the captcha and rigorous mitigations if you just try to sign-in from a new IP.

**Comment by Pascalmh** [comment]
Yes, we run it on CI - but only once a day, we use the `AmazonSocialLogin` with 2FA enabled.

**Comment by lirantal** [comment]
Thanks. How do you pass through the 2FA part? or is that why you have the pre-visit cookie pull request? :)

**Comment by Pascalmh** [comment]
We use the `otpSecret`-option to fill in the 2FA Code. The pre-visit cookie is used to enable a feature (feature toggled).

**Comment by lirantal** [comment]
Ahh got it. Thanks!

**Pull request merged**
