### PR TITLE
feat: export baseLoginConnect function

### LINKED ISSUE #58: Create an Export function for Custom Logins
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve. 
I've been looking plugins or methods for login such as Request and Visit to provide login credentials to a website, (Steam.com in this case,) which I use to explore ways how to test or improve setup, instead of going to front end approach by finding and run send keys. Sadly, attempting to login this Steam.com using Request or Visit, doesn't appear to be working. I get a 200 response code, but upon refresh/reload, it doesn't appear the login worked.
I see you have a list of providers which can be passed into Cypress task(). After inspecting your function's to perform the login, I want to try the login approach using your plugin.  
Would you be willing to provide an export function where users to can define the selectors they next to select to provide the user's own selectors to type or select submit buttons/tags?

**Describe the solution you'd like**
Please describe the desired behavior.
I was thinking the best way to define the selectors and buttons would be to provide more properties which are accepted by the Options property. (Ex: customUsernameSelector, customLoginSubmit, etc).

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

### PR DESCRIPTION
**Pull request by fkropfhamer**
Export baseLoginConnect function

Export the baseLoginConnect function to allow providing custom typeUsername, typePassword and authorizeApp for custom logins.

## Description
Added baseLoginConnect function to exports

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Fixed https://github.com/lirantal/cypress-social-logins/issues/58

[https://github.com/lirantal/cypress-social-logins/issues/58](url)

## How Has This Been Tested?

Test in example application, which uses custom OAuth login

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
This is it?

**Comment by fkropfhamer** [comment]
I want to add support for facebook login later, but for the moment this would be enough.

**Comment by lirantal** [comment]
Coolness! Let me merge and get a new version out

**Comment by fkropfhamer** [comment]
Thanks a lot!

**Pull request merged**
