### PR TITLE
Add support for Facebook login

### PR DESCRIPTION
**Pull request by Gogowitsch**
## Description
This pull request adds support for Facebook. In addition, I fixed small readability issues with the documentation. 

Also, the examples in the README.md were broken, so I fixed them. To clarify: these were not bug fixes in .js files, just the documentation.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue
Issue #27 is incorrectly marked as closed. This pull request resolves it.

## How Has This Been Tested?
Tested as part of my project.

## Checklist:
- [x] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
This is great @Fonata, thanks a bunch! ❤️

**Comment by michaltalaga** [comment]
@lirantal - when do you plan to have this released? need it soo much

**Comment by lirantal** [comment]
@michaltalaga ahh indeed, looks like I messed up the semantic commit message style (forgetting a colon) so I just pushed a new one and it should trigger a job and a new npm release soon. I'll ping when I see it published.

**Comment by lirantal** [comment]
@michaltalaga  included in new release now too!

**Comment by michaltalaga** [comment]
@Fonata  this doesn't seem to work. I'm stuck at 
image
how do you handle cookie consent?

**Comment by lirantal** [comment]
Check the updated README for options. There's a new one option to click on popups if I remember correctly.

**Comment by Gogowitsch** [comment]
@michaltalaga About the Cookie consent: I didn't see this during my tests. I am not aware of any steps we took to prevent the popup. It worked both on native Ubuntu 20 and within Docker. 

I don't think it is related with the consent at all, but we did set the `isPopup` option:
```js
        const socialLoginOptions = {
            ...
            isPopup: true,
        };
```

If anyone here has a hunch on when / why the Cookie consent appears, let me know. I cannot fix it if it doesn't happen for me.

**Comment by patcon** [comment]
I'm sure this is a new issue, but just wanted to flag this for the next person who's troubleshooting, in case I don't get around to submitting a fix:

- Seems that this will only work on the first sign up, since the permission confirmation screen isn't shown after the user has already auth'd the app. So testing a return user will fail. Perhaps this is expected. (This manifests as Cypress complaining that the target window has been closed, since it closed before the confirmation selector check.
- For someone reason, I needed to add this right before the `await browser.pages()` line, otherwise the text fields aren't recognized in the popup:

  ```js
  await new Promise(x => browser.once('targetcreated', target => x(target.page()))
  ```

https://github.com/lirantal/cypress-social-logins/blob/3cd9f8cb5b8b1f6dc2448e6e44d18e8536515918/src/Plugins.js#L192-L203

I found the code that fixed this here: 
https://stackoverflow.com/questions/46669788/how-to-handle-popups-in-puppeteer

**Comment by patcon** [comment]
Anyhow, thanks very much! I'm open to advice, and might have time to come back to this :)

**Comment by Gogowitsch** [comment]
@patcon 
- Regarding the confirmation screen: I created PR #70 to fix this. We ran into this as well, but only after many logins all previous logins for the same user had the confirmation page. Facebook is a bit of a mystery, apparently. 
- Regarding the `targetcreated` event: Cool!  
  We use the `popupDelay: 2000` option instead.  
  Personally, I don't plan to open a PR for this problem because I don't know Puppeteer well enough yet. I suppose this affects all popup-based logins, not just Facebook. Feel free to open a PR, though

**Comment by michaltalaga** [comment]
none of the above works for me unfortunately
interestingly now my cookie consent shows up after user & password is typed in.
also I do NOT get it when I just do incognito mode in my browser. chrome and edge. sent it to a random friend. He's not getting that....

strange.

There seems to be a way to pre-populate cookies to prevent the consent dialog will try to play with that and send a PR if I find a clean workaround

**Comment by patcon** [comment]
Thanks for reply @Fonata :)

@michaltalaga Fwiw I don't get any cookie consent thing. Guessing it's due to your country (UK)? A workaround might be to (1) create a digital ocean server and run cypress there, or (2) cheap/free VPN. Though obviously if you fixed it, others would surely benefit from pushing a real fix upstream :)

**Comment by michaltalaga** [comment]
I thought it may be country related but at least one of my friend who is uk base does not get the cookie consent.

**Comment by patcon** [comment]
Might have to do with actual metadata of facebook account (home address or something?). Just a wild guess tho. Who knows how Facebook guesses if someone's a UK citizen :)

**Comment by michaltalaga** [comment]
It's pre login though...

**Comment by anukem** [comment]
Would it be possible to add a code sample for the Facebook Login. I'm currently trying it out now and having issues getting the loaded page to send back the cookies. Here's the error I've been getting. 
image

**Comment by patcon** [comment]
@ezeugoanukem I didn't actually get it worrrrking, but I had troubleshot through a few things, and this was what I had (for login in a popup): https://github.com/pol-is/polis/compare/541-fb-login-tests

Also, for popup login only, I had to fork the plugin and add the one-liner as described in https://github.com/lirantal/cypress-social-logins/pull/67#issuecomment-739464108

**Comment by anukem** [comment]
what were you using for the loginUrl?

**Comment by anukem** [comment]
Got it working! Turns out all I needed was that additional arg you passed in to ignore cert errors since I'm running the test locally. Thank you.

**Comment by lirantal** [comment]
Great to see this resolved.
If one of you @patcon @ezeugoanukem wanted to add a quick troubleshooting note on the README about adding the following arg as in https://github.com/pol-is/polis/compare/541-fb-login-tests#diff-badf62ace34efd48a76f68587dfe56ce5f9d828e97be356dd4cd3a13d4d99effR32 that would be nice and helpful to other users I believe.

**Pull request merged**
