### PR TITLE
Make cypress-social-logins compatible with TypeScript imports

### PR DESCRIPTION
**Pull request by InvisibleExo**
## Description

Added` .d.ts `versions for `Plugins.js` and `index.js` in order this package to be compatible with imports in TypeScript files.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Adding the `.d.ts` files for this package will allow TypeScript files be able to import this package while using the same `.js` files. However, for future functions added to `Plugins.js `they will next to be declared and exported in `Plugins.d.ts` as well.

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks @InvisibleExo 👏

**Comment by InvisibleExo** [comment]
@lirantal minor hiccup I failed to notice was if user imports the package for any of the functions while in Typescript. It will import from 'cypress-social-logins/src/Plugins'  instead from package name. Though the import the functions from there, the functions will run in Cypress without issue.

**Comment by lirantal** [comment]
What does it mean?
I'm not using TypeScript here so I'm not sure what impact this has.

**Comment by InvisibleExo** [comment]
It doesn't have a functional impact, though the concern would be confusion if user assumes they can import functions by package name. VS code editors seem smart enough to correct the import path.

**Pull request merged**
