### PR TITLE
test: add cypress as e2e in project

### PR DESCRIPTION
**Pull request by lirantal**
## Description

Add E2E tests to this project that confirm that this plugin works well with a sample website test as a scenario.

## Types of changes

- [x] Test
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by lirantal** [comment]
Last CI step fails with:

```
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"

tput: No value for $TERM and no -T specified
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.0.2                                                                              │
  │ Browser:    Electron 78 (headless)                                                             │
  │ Specs:      1 found (Dashboard.spec.js)                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  Dashboard.spec.js                                                               (1 of 1)


  Account Dashboard
    Login
      1) Login through Google
    Homepage view
      2) User account sub-navs listed


  0 passing (6s)
  2 failing

  1) Account Dashboard Login Login through Google:
     CypressError: cy.task('GoogleSocialLogin') failed with the following error:

> Error: Failed to launch the browser process!
[0216/093706.647650:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/project/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/root/project/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:208:15)
    at Interface.close (readline.js:403:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
      at cypressErr (https://app.snyk.io/__cypress/runner/cypress_runner.js:149934:9)
      at throwErr (https://app.snyk.io/__cypress/runner/cypress_runner.js:149867:11)
      at Object.throwErrByPath (https://app.snyk.io/__cypress/runner/cypress_runner.js:149915:3)
      at https://app.snyk.io/__cypress/runner/cypress_runner.js:140354:26
      at tryCatcher (https://app.snyk.io/__cypress/runner/cypress_runner.js:167415:23)
      at Promise._settlePromiseFromHandler (https://app.snyk.io/__cypress/runner/cypress_runner.js:165351:31)
      at Promise._settlePromise (https://app.snyk.io/__cypress/runner/cypress_runner.js:165408:18)
      at Promise._settlePromise0 (https://app.snyk.io/__cypress/runner/cypress_runner.js:165453:10)
      at Promise._settlePromises (https://app.snyk.io/__cypress/runner/cypress_runner.js:165528:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://app.snyk.io/__cypress/runner/cypress_runner.js:162140:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://app.snyk.io/__cypress/runner/cypress_runner.js:162150:10)
      at Async.drainQueues (https://app.snyk.io/__cypress/runner/cypress_runner.js:162024:14)
  2) Account Dashboard Homepage view User account sub-navs listed:
     CypressError: Timed out retrying: Expected to find element: '.vue--section-header', but never found it.
      at cypressErr (https://app.snyk.io/__cypress/runner/cypress_runner.js:149934:9)
      at throwErr (https://app.snyk.io/__cypress/runner/cypress_runner.js:149867:11)
      at Object.throwErrByPath (https://app.snyk.io/__cypress/runner/cypress_runner.js:149915:3)
      at retry (https://app.snyk.io/__cypress/runner/cypress_runner.js:144197:19)
      at onFailFn (https://app.snyk.io/__cypress/runner/cypress_runner.js:132448:16)
      at tryCatcher (https://app.snyk.io/__cypress/runner/cypress_runner.js:167415:23)
      at Promise._settlePromiseFromHandler (https://app.snyk.io/__cypress/runner/cypress_runner.js:165351:31)
      at Promise._settlePromise (https://app.snyk.io/__cypress/runner/cypress_runner.js:165408:18)
      at Promise._settlePromise0 (https://app.snyk.io/__cypress/runner/cypress_runner.js:165453:10)
      at Promise._settlePromises (https://app.snyk.io/__cypress/runner/cypress_runner.js:165528:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://app.snyk.io/__cypress/runner/cypress_runner.js:162140:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://app.snyk.io/__cypress/runner/cypress_runner.js:162150:10)
      at Async.drainQueues (https://app.snyk.io/__cypress/runner/cypress_runner.js:162024:14)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      2                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  2                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     Dashboard.spec.js                                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

  (Screenshots)

  -  /root/project/cypress/screenshots/Dashboard.spec.js/Account Dashboard -- Login -     (1280x720)
     - Login through Google (failed).png                                                            
  -  /root/project/cypress/screenshots/Dashboard.spec.js/Account Dashboard -- Homepag     (1280x720)
     e view -- User account sub-navs listed (failed).png                                            


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /root/project/cypress/videos/Dashboard.spec.js.mp4              (1 second)


tput: No value for $TERM and no -T specified
====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  Dashboard.spec.js                        00:06        2        -        2        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:06        2        -        2        -        -  

Exited with code exit status 2
```

**Comment by mirzamusic** [comment]
now this can pass if you provide in options `args: ['--no-sandbox', '--disable-setuid-sandbox']`

**Comment by lirantal** [comment]
@mirzamusic I did update the code to pass that but it looks like the issue is with puppeteer which I can't see a screen recording of. Would need to further drill into this...

**Comment by shivasrini** [comment]
@lirantal I had the same problem and I even created an issue for it to see if you can help me out but turns out I was not passing the args parameter in my test. But fwiw I only passed the --no-sandbox and did not pass the --disable-setuid-sandbox and that did the trick for me but I was also running chrome and not electron

**Comment by lirantal** [comment]
thanks @shivasrini, I updated the tests, let's try now to see if it helps.

**Comment by lirantal** [comment]
thanks for the help with this @mirzamusic 
it is failing on lint:

image

**Comment by mirzamusic** [comment]
> it is failing on lint:

sure, I always forgot to run lint fix :/

**Comment by mirzamusic** [comment]
@lirantal now we have a different issue,
can you check whats happens  here https://dashboard.cypress.io/projects/99u316/runs/3

**Comment by lirantal** [comment]
@mirzamusic you should have access now to the Cypress dashboard.

**Comment by zakhenry** [comment]
@lirantal I'm curious what issue is happening here on CI as I'm using this plugin successfully locally, but I have CI issues. I'm wondering if it is the same problem

**Comment by zakhenry** [comment]
In my case I get the following sequence of urls:

```
Puppeteer visited url:  http://localhost:3000/(authentication:auth/login)
 Puppeteer visited url:  http://localhost:3000/assets/loader.svg
 Puppeteer visited url:  about:blank
 Puppeteer visited url:  http://localhost:3000/(authentication:auth/login)
 Puppeteer visited url:  chrome-error://chromewebdata/
```

(my loginUrl is `http://localhost:3000/(authentication:auth/login)` )

this is generated by inserting the following into the plugin
```
  page.on('framenavigated', frame => {
    console.log('Puppeteer visited url: ', frame._url);
  });
```

**Comment by lirantal** [comment]
@zakhenry right, works fine for me locally too :)
I think the issue with CI is due to the OS setup not having a windowing system (XWindows kind of thing) for puppetteer.

In case it helps identify the issue, these are the errors I'm getting on CI:

```
#!/bin/bash -eo pipefail 
npx cypress run \ 
   \ 
   \ 
   \ 
   --record \ 
     \ 
     \ 
     \ 
 
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
 

 
tput: No value for $TERM and no -T specified
 
====================================================================================================
 

 
  (Run Starting)
 

 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
 
  │ Cypress:    4.1.0                                                                              │
 
  │ Browser:    Electron 78 (headless)                                                             │
 
  │ Specs:      1 found (Dashboard.spec.js)                                                        │
 
  │ Params:     Tag: false, Group: false, Parallel: false                                          │
 
  │ Run URL:    https://dashboard.cypress.io/projects/99u316/runs/3                                │
 
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
 

 

 
────────────────────────────────────────────────────────────────────────────────────────────────────
 
                                                                                                    
 
  Running:  Dashboard.spec.js                                                               (1 of 1)
 
  Estimated: 39 seconds
 

 

 
  Account Dashboard
 
    Login
 
      1) Login through Google
 
    Homepage view
 
      2) User account sub-navs listed
 

 

 
  0 passing (38s)
 
  2 failing
 

 
  1) Account Dashboard Login Login through Google:
 
     CypressError: cy.task('GoogleSocialLogin') failed with the following error:
 

 
> TimeoutError: waiting for selector ".account-panel" failed: timeout 30000ms exceeded
 
    at new WaitTask (/root/project/node_modules/puppeteer/lib/DOMWorld.js:549:28)
 
    at DOMWorld._waitForSelectorOrXPath (/root/project/node_modules/puppeteer/lib/DOMWorld.js:478:22)
 
    at DOMWorld.waitForSelector (/root/project/node_modules/puppeteer/lib/DOMWorld.js:432:17)
 
    at Frame.waitForSelector (/root/project/node_modules/puppeteer/lib/FrameManager.js:627:47)
 
    at Frame.<anonymous> (/root/project/node_modules/puppeteer/lib/helper.js:112:23)
 
    at Page.waitForSelector (/root/project/node_modules/puppeteer/lib/Page.js:1122:29)
 
    at getCookies (/root/project/src/Plugins.js:122:14)
 
    at GoogleSocialLogin (/root/project/src/Plugins.js:69:25)
 
      at cypressErr (https://app.snyk.io/__cypress/runner/cypress_runner.js:138036:9)
 
      at throwErr (https://app.snyk.io/__cypress/runner/cypress_runner.js:137969:11)
 
      at Object.throwErrByPath (https://app.snyk.io/__cypress/runner/cypress_runner.js:138017:3)
 
      at https://app.snyk.io/__cypress/runner/cypress_runner.js:128445:26
 
      at tryCatcher (https://app.snyk.io/__cypress/runner/cypress_runner.js:164895:23)
 
      at Promise._settlePromiseFromHandler (https://app.snyk.io/__cypress/runner/cypress_runner.js:162831:31)
 
      at Promise._settlePromise (https://app.snyk.io/__cypress/runner/cypress_runner.js:162888:18)
 
      at Promise._settlePromise0 (https://app.snyk.io/__cypress/runner/cypress_runner.js:162933:10)
 
      at Promise._settlePromises (https://app.snyk.io/__cypress/runner/cypress_runner.js:163008:18)
 
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://app.snyk.io/__cypress/runner/cypress_runner.js:159620:16)
 
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://app.snyk.io/__cypress/runner/cypress_runner.js:159630:10)
 
      at Async.drainQueues (https://app.snyk.io/__cypress/runner/cypress_runner.js:159504:14)
 

 
  2) Account Dashboard Homepage view User account sub-navs listed:
 
     CypressError: Timed out retrying: Expected to find element: '.vue--section-header', but never found it.
 
      at cypressErr (https://app.snyk.io/__cypress/runner/cypress_runner.js:138036:9)
 
      at throwErr (https://app.snyk.io/__cypress/runner/cypress_runner.js:137969:11)
 
      at Object.throwErrByPath (https://app.snyk.io/__cypress/runner/cypress_runner.js:138017:3)
 
      at retry (https://app.snyk.io/__cypress/runner/cypress_runner.js:132299:19)
 
      at onFailFn (https://app.snyk.io/__cypress/runner/cypress_runner.js:120514:16)
 
      at tryCatcher (https://app.snyk.io/__cypress/runner/cypress_runner.js:164895:23)
 
      at Promise._settlePromiseFromHandler (https://app.snyk.io/__cypress/runner/cypress_runner.js:162831:31)
 
      at Promise._settlePromise (https://app.snyk.io/__cypress/runner/cypress_runner.js:162888:18)
 
      at Promise._settlePromise0 (https://app.snyk.io/__cypress/runner/cypress_runner.js:162933:10)
 
      at Promise._settlePromises (https://app.snyk.io/__cypress/runner/cypress_runner.js:163008:18)
 
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://app.snyk.io/__cypress/runner/cypress_runner.js:159620:16)
 
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://app.snyk.io/__cypress/runner/cypress_runner.js:159630:10)
 
      at Async.drainQueues (https://app.snyk.io/__cypress/runner/cypress_runner.js:159504:14)
 

 

 

 

 
  (Results)
 

 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
 
  │ Tests:        2                                                                                │
 
  │ Passing:      0                                                                                │
 
  │ Failing:      2                                                                                │
 
  │ Pending:      0                                                                                │
 
  │ Skipped:      0                                                                                │
 
  │ Screenshots:  2                                                                                │
 
  │ Video:        true                                                                             │
 
  │ Duration:     37 seconds                                                                       │
 
  │ Estimated:    39 seconds                                                                       │
 
  │ Spec Ran:     Dashboard.spec.js                                                                │
 
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
 

 

 
  (Screenshots)
  
tput: No value for $TERM and no -T specified
 
====================================================================================================
 

 
  (Run Finished)
 

 

 
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
 
  │ ✖  Dashboard.spec.js                        00:37        2        -        2        -        - │
 
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
 
    ✖  1 of 1 failed (100%)                     00:37        2        -        2        -        -  
 

 

 
```

**Comment by zakhenry** [comment]
@lirantal that looks very similar to what I'm seeing. Can you try putting the logging that I mentioned above into your code to see if you get the same redirection to `chrome-error://chromewebdata` ? 

I tried a tonne of different Chromium flags, but to no avail I'm afraid

**Comment by lirantal** [comment]
What will it teach us though? I think the issue is getting a proper Window-ed environment, no?

**Comment by zakhenry** [comment]
I'm not entirely sure, to be honest. Maybe just another data point to narrow the error scenario

**Comment by lirantal** [comment]
Where exactly should I add that console output?

**Comment by zakhenry** [comment]
It is an event listener, so I inserted it directly after the `let page = await browser.newPage()` line.

Here's a snippet:

```js
  const browser = await puppeteer.launch(launchOptions)
  let page = await browser.newPage()

  page.on('framenavigated', frame => {
    console.log('Puppeteer visited url: ', frame._url);
  });

  page.on('pageerror', pageerr=> {
    console.log('pageerror occurred: ', pageerr);
  });

  let originalPageIndex = 1
  await page.setViewport({width: 1280, height: 800})
```

**Comment by wadehammes** [comment]
Was just about to post a bug report but this seems related. I am having an issue of `waiting for selector "input[type="email"]" failed: timeout 30000ms exceeded` once it opens the popup (Im running this with `headless: false` so I can actually see what's happening.

**Comment by wadehammes** [comment]
Im experiencing this as well. Everything works fine locally and if using `headless: false` but I get the same error above if running headless.

**Comment by lirantal** [comment]
`headless: false` works fine in CI? if so, which CI is it?

**Comment by wadehammes** [comment]
Sorry, I meant locally `headless: false` is working. I’m getting same error
above locally and in CI with `headless: true`.

**Comment by lirantal** [comment]
@mirzamusic @wadehammes @zakhenry 
so I actually have fixed up everything with regards to this plugin working in CI, it completes the username and password steps just fine, but then due to the account being used by an unknown user agent, and the IP being different then the login process receives the following:

image

if you have ideas how to continue from this point on let me know.

**Comment by lirantal** [comment]
Closed in favor of up to date branch using GitHubSocialLogin here: https://github.com/lirantal/cypress-social-logins/compare/master...tests/add-cypress-e2e-second-go

Note: Still not exactly functional from CI as it requires an email verification due to the login from a diff browser/location. Keeping the branch as a reference.

**Pull request closed without merging**
