### PR TITLE
feat: add support for GitHub and Microsoft social logins

### PR DESCRIPTION
**Pull request by vikmaksymenko**
Added support of GitHub and Microsoft

Refactor Plugins.js to handle multiple social logins

## Description

Updated Plugins.js and added support of GitHub and Microsoft sign in

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

https://github.com/lirantal/cypress-social-logins/issues/52

## Motivation and Context

Needed GitHub and Microsoft support for testing the app.

## How Has This Been Tested?

Was using it in testing project

## Checklist:

- [x] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks @vikmaksimenko, I'll set some time to review and test later today/tomorrow.

**Review by lirantal — APPROVED** [review]
I tested the Google and GitHub logins, looks great! 🚀

**Comment by lirantal** [comment]
Thanks @vikmaksimenko ❤️❤️❤️

**Comment by clatkar-spurqlabs** [comment]
try this recipe for SSO with MFA for Office 365 :-https://spurqlabs.com/login-to-o365-sso-enabled-application-with-mfa-using-cypress-10/

**Pull request merged**
