### PR TITLE
fix: avoid typing in application inputs

### LINKED ISSUE #30: Email is entered in application email button due to absez
Please describe the problem you are trying to solve.
My page has an email input, with 'input[type="email"]'. Immediately the sign in button is clicked, the plugin does not wait till the browser redirects rather, it starts entering the the email on my page's email field

**Describe the solution you'd like**
Email is typed only when clicking on login selector has completely redirected
Please describe the desired behavior.

**Describe alternatives you've considered**
An option to add a delay before entering the email, so that the page redirects before email is typed
Please describe alternative solutions or features you have considered.

### PR DESCRIPTION
**Pull request by mpoehler**
See Video in Issue #30 for explaination. I just made the selector a little more precise.

closes #30  

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

#30 

## Motivation and Context

See Issue #30 for Video and Context

## Screenshots (if appropriate):

Video with changed selectors: 
https://drive.google.com/file/d/1kUo-QifFAIpmUyN_3bZtYLr4U0iTpc_A/view?usp=sharing

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by lirantal** [comment]
@mpoehler so the fix here is due to the use of the specific id `identiferId` on the input field which the app itself doesn't have?


I just merged now a bigger PR with support for GitHub and Microsoft login providers so this PR needs to be rebased for the small fix to apply on the changed source code. If it's easier for you we can just close this PR and you can open a new one for the updated changes from master.

Thanks for sending this in.

**Comment by mpoehler** [comment]
@lirantal Yes, only the selector is made more specific. You could probably also solve it with a delay, as @yusufJinadu wrote, but then you are always dependent on the loading speed of your provider. In case of doubt, there will be an unnecessary delay. Therefore I decided to use the selector.

**Comment by mpoehler** [comment]
Yes, I will close this PR here right now and open a new one. I also accidentally included the yarn.lock in the commit. I will do better next time.

**Comment by lirantal** [comment]
Sounds good, thanks!

**Pull request closed without merging**
