### PR TITLE
Adding CustomizedLogin Function and Logic for AdditionalSteps

### PR DESCRIPTION
**Pull request by InvisibleExo**
## Description

Two additions were added to `Plugins.js` 

1.  Function `CustomizedLogin` was added for users to provide their own selectors for username and password instead of only defining the function in Cypress plugins. 

2. `options.additionalSteps` was provided in the workflow for `baseLoginConnect` function right after `typePassword()` for cases where there may be additional steps for the login process after entering the pw.  `additionalSteps` function must be assigned to the `options` object in `index.js` for Cypress Plugins, which functions defining the additional steps must be added or referenced in the same file. (Documentation has been added to the ReadMe.md

Troubleshoot information regarding correct selector format has been added to ReadMe.md

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

Ran several E2E cases,  where options.additionalSteps are applied and not applied. I also tested CustomizedLogin function, as well scenarios where username and pw fields weren't add to `options` object.

## Checklist:

- [ x ] I have updated the documentation (if required).
- [ x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by InvisibleExo** [comment]
Can I please get a review?

**Comment by lirantal** [comment]
Will take a look tomorrow! 🙏

**Comment by InvisibleExo** [comment]
Yay. Thank you for reviewing.

**Comment by lirantal** [comment]
@InvisibleExo included in new release now too!

**Pull request merged**
